=== bartoszPawlicki/PCK/dtdfile.dtd
<!ELEMENT płytoteka (nagłówek, zbiór)>

<!ELEMENT nagłówek (autor+, opis, dataAktualizacji)>
<!ELEMENT autor (imię+, nazwisko+, nrIndeksu?)>
<!ATTLIST autor id ID #REQUIRED>
<!ELEMENT imię (#PCDATA)>
<!ELEMENT nazwisko (#PCDATA)>
<!ELEMENT nrIndeksu (#PCDATA)>
<!ELEMENT opis (#PCDATA)>
<!ELEMENT dataAktualizacji (#PCDATA)>


<!ELEMENT zbiór (płyta*, wykonawcy)>
<!ATTLIST zbiór nazwa NMTOKENS #IMPLIED>

<!ELEMENT płyta (tytuł, wykonawca+, liczbaUtworów, dataWydania, cena, utwory)>
<!ATTLIST płyta gatunek (rock | metalcore | metal | progressive-death-metal | punk-rock | rap | pop | hip-hop | niezdefiniowany) "niezdefiniowany">
<!ELEMENT tytuł (#PCDATA)>
<!ELEMENT wykonawca EMPTY>
<!ATTLIST wykonawca idwykonawcy IDREF #REQUIRED>
<!ELEMENT liczbaUtworów (#PCDATA)>
<!ELEMENT dataWydania (#PCDATA)>
<!ELEMENT cena (#PCDATA)>
<!ATTLIST cena waluta (zł | euro | dolar) "zł" >

<!ELEMENT utwory (lista)>
<!ATTLIST utwory nazwa NMTOKENS #IMPLIED>
<!ELEMENT lista (utwór+)>
<!ELEMENT utwór (tytułUtworu, czasTrwania)>
<!ATTLIST utwór codec (mp3 | flac | ogg) "mp3">
<!ATTLIST utwór bitrate NMTOKEN "320">
<!ELEMENT tytułUtworu (#PCDATA)>
<!ELEMENT czasTrwania (#PCDATA)>



<!ELEMENT wykonawcy (wyk*)>
<!ELEMENT wyk (#PCDATA)>
<!ATTLIST wyk idwykonawcy ID #REQUIRED>]>

=== bartoszPawlicki/PCK/plytoteka.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!-- <!DOCTYPE płytoteka SYSTEM "dtdfile.dtd"> /!-->
<?xml-stylesheet type="text/css" href="style.css" ?>

<płytoteka xmlns="http://www.w3schools.com"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.w3schools.com xsdfile.xsd">
    
    <nagłówek>
        <autor id="a1"> 
			<imię>Bartosz</imię> 
			<nazwisko>Pawlicki</nazwisko>
			<nrIndeksu>195678</nrIndeksu>
		</autor>
        <autor id="a2"> 
			<imię>Piotr</imię> 
			<nazwisko>Adryjańczyk</nazwisko>
			<nrIndeksu>195555</nrIndeksu>
		</autor>
        <opis> Zadanie 1 - Użycie CSS do formatowania XML plus definicja DTD </opis>
        <dataAktualizacji> 2016-10-08 </dataAktualizacji>
    </nagłówek>
    
	
	
    <zbiór nazwa="ZBIÓR PŁYT">
        <płyta gatunek="rock">
            <tytuł> L.A. Woman </tytuł>
            <wykonawca idwykonawcy="w0"></wykonawca>
            <liczbaUtworów> 10 </liczbaUtworów>
            <dataWydania> 1971-05-24 </dataWydania>
            <cena waluta="zł">45</cena>
            <utwory nazwa= "Lista utworów">
				<lista>			
				<utwór codec="mp3" bitrate="320">
					<tytułUtworu>The Changeling</tytułUtworu>
					<czasTrwania>4:21</czasTrwania>
				</utwór>
                <utwór codec="mp3" bitrate="320">
					<tytułUtworu>Love Her Madly</tytułUtworu>
					<czasTrwania>3:20</czasTrwania>
				</utwór>
                <utwór codec="mp3" bitrate="320">
					<tytułUtworu>Riders on the Storm</tytułUtworu>
					<czasTrwania>7:09</czasTrwania>
				</utwór>
				</lista>
			</utwory>
        </płyta>
        
        <płyta gatunek="metalcore">
            <tytuł> The Poison </tytuł>
            <wykonawca idwykonawcy="w1"></wykonawca>
            <liczbaUtworów> 13 </liczbaUtworów>
            <dataWydania> 2005-10-03 </dataWydania>
            <cena waluta="zł">33.33</cena>
            <utwory nazwa= "Lista utworów"> 
				<lista>	
				<utwór codec="flac" bitrate="320">
					<tytułUtworu>4 Words (To Choke Upon)</tytułUtworu>
					<czasTrwania>3:43</czasTrwania>
				</utwór>
                <utwór codec="flac" bitrate="320">
					<tytułUtworu>Tears Don't Fall</tytułUtworu>
					<czasTrwania>5:48</czasTrwania>
				</utwór>
                <utwór codec="flac" bitrate="320">
					<tytułUtworu>All These Things I Hate</tytułUtworu>
					<czasTrwania>3:45</czasTrwania>
				</utwór>
				</lista>
			</utwory>
        </płyta>
        
        <płyta gatunek="rap">
            <tytuł> VanillaHaj$ </tytuł>
            <wykonawca idwykonawcy="w2"></wykonawca>
            <liczbaUtworów> 16 </liczbaUtworów>
            <dataWydania> 2016-04-23 </dataWydania>
            <cena waluta="zł">38</cena>
            <utwory nazwa= "Lista utworów"> 
				<lista>	
				<utwór codec="ogg" bitrate="320">
					<tytułUtworu>Vanillalalahajs</tytułUtworu>
					<czasTrwania>3:04</czasTrwania>
				</utwór>
                <utwór codec="ogg" bitrate="320">
					<tytułUtworu>Vanilla Ice</tytułUtworu>
					<czasTrwania>4:22</czasTrwania>
				</utwór>
                <utwór codec="ogg" bitrate="320">
					<tytułUtworu>Dyskretny chłód 2</tytułUtworu>
					<czasTrwania>3:56</czasTrwania>
				</utwór>
				</lista>
			</utwory>
        </płyta>
        
        <płyta gatunek="progressive-death-metal">
            <tytuł>Orchid</tytuł>
            <wykonawca idwykonawcy="w3"></wykonawca>
            <liczbaUtworów> 7 </liczbaUtworów>
            <dataWydania> 1995-05-01 </dataWydania>
            <cena waluta="euro">29.99</cena>
            <utwory nazwa= "Lista utworów"> 
				<lista>	
				<utwór codec="mp3" bitrate="320">
					<tytułUtworu>In Mist She Was Standing</tytułUtworu>
					<czasTrwania>14:09</czasTrwania>
				</utwór>
                <utwór codec="mp3" bitrate="320">
					<tytułUtworu>Under the Weeping Moon</tytułUtworu>
					<czasTrwania>9:55</czasTrwania>
				</utwór>
                <utwór codec="mp3" bitrate="320">
					<tytułUtworu>Silhouette</tytułUtworu>
					<czasTrwania>3:04</czasTrwania>
				</utwór>
				</lista>
			</utwory>
        </płyta>
        
        <płyta gatunek="punk-rock">
            <tytuł>Smash</tytuł>
            <wykonawca idwykonawcy="w4"></wykonawca>
            <liczbaUtworów> 14 </liczbaUtworów>
            <dataWydania> 1994-04-08 </dataWydania>
            <cena waluta="zł">50.00</cena>
            <utwory nazwa= "Lista utworów"> 
				<lista>	
				<utwór codec="mp3" bitrate="252">
					<tytułUtworu>Self Esteem</tytułUtworu>
					<czasTrwania>4:17</czasTrwania>
				</utwór>
               <utwór codec="mp3" bitrate="252">
					<tytułUtworu>Come Out and Play</tytułUtworu>
					<czasTrwania>3:17</czasTrwania>
				</utwór>
                <utwór codec="mp3" bitrate="252">
					<tytułUtworu>Nitro (Youth Energy)</tytułUtworu>
					<czasTrwania>2:27</czasTrwania>
				</utwór>
				</lista>
			</utwory>
        </płyta>
        <płyta gatunek="punk-rock">
            <tytuł>Americana</tytuł>
            <wykonawca idwykonawcy="w4"></wykonawca>
            <liczbaUtworów> 13 </liczbaUtworów>
            <dataWydania> 2005-01-08 </dataWydania>
            <cena waluta="zł">25.00</cena>
            <utwory nazwa= "Lista utworów"> 
				<lista>	
				<utwór codec="mp3" bitrate="320">
					<tytułUtworu>Pretty Fly (for a White Guy)</tytułUtworu>
					<czasTrwania>3:08</czasTrwania>
				</utwór>
               <utwór codec="mp3" bitrate="320">
					<tytułUtworu>The Kids Aren’t Alright</tytułUtworu>
					<czasTrwania>3:00</czasTrwania>
				</utwór>
                <utwór codec="mp3" bitrate="320">
					<tytułUtworu>Americana</tytułUtworu>
					<czasTrwania>3:15</czasTrwania>
				</utwór>
				</lista>
			</utwory>
        </płyta>
        <płyta gatunek="punk-rock">
            <tytuł>Americana</tytuł>
            <wykonawca idwykonawcy="w4"></wykonawca>
            <liczbaUtworów> 13 </liczbaUtworów>
            <dataWydania> 2005-01-08 </dataWydania>
            <cena waluta="zł">25.00</cena>
            <utwory nazwa= "Lista utworów"> 
				<lista>	
				<utwór codec="mp3" bitrate="320">
					<tytułUtworu>Pretty Fly (for a White Guy)</tytułUtworu>
					<czasTrwania>3:08</czasTrwania>
				</utwór>
               <utwór codec="mp3" bitrate="320">
					<tytułUtworu>The Kids Aren’t Alright</tytułUtworu>
					<czasTrwania>3:00</czasTrwania>
				</utwór>
                <utwór codec="mp3" bitrate="320">
					<tytułUtworu>Americana</tytułUtworu>
					<czasTrwania>3:15</czasTrwania>
				</utwór>
				</lista>
			</utwory>
        </płyta>
        <płyta gatunek="punk-rock">
            <tytuł>Americana</tytuł>
            <wykonawca idwykonawcy="w4"></wykonawca>
            <liczbaUtworów> 13 </liczbaUtworów>
            <dataWydania> 2005-01-08 </dataWydania>
            <cena waluta="zł">25.00</cena>
            <utwory nazwa= "Lista utworów"> 
				<lista>	
				<utwór codec="mp3" bitrate="320">
					<tytułUtworu>Pretty Fly (for a White Guy)</tytułUtworu>
					<czasTrwania>3:08</czasTrwania>
				</utwór>
               <utwór codec="mp3" bitrate="320">
					<tytułUtworu>The Kids Aren’t Alright</tytułUtworu>
					<czasTrwania>3:00</czasTrwania>
				</utwór>
                <utwór codec="mp3" bitrate="320">
					<tytułUtworu>Americana</tytułUtworu>
					<czasTrwania>3:15</czasTrwania>
				</utwór>
				</lista>
			</utwory>
        </płyta>
        <płyta gatunek="punk-rock">
            <tytuł>Americana</tytuł>
            <wykonawca idwykonawcy="w4"></wykonawca>
            <liczbaUtworów> 13 </liczbaUtworów>
            <dataWydania> 2005-01-08 </dataWydania>
            <cena waluta="zł">25.00</cena>
            <utwory nazwa= "Lista utworów"> 
				<lista>	
				<utwór codec="mp3" bitrate="320">
					<tytułUtworu>Pretty Fly (for a White Guy)</tytułUtworu>
					<czasTrwania>3:08</czasTrwania>
				</utwór>
               <utwór codec="mp3" bitrate="320">
					<tytułUtworu>The Kids Aren’t Alright</tytułUtworu>
					<czasTrwania>3:00</czasTrwania>
				</utwór>
                <utwór codec="mp3" bitrate="320">
					<tytułUtworu>Americana</tytułUtworu>
					<czasTrwania>3:15</czasTrwania>
				</utwór>
				</lista>
			</utwory>
        </płyta>
		
		<wykonawcy>
			<wyk idwykonawcy="w0">The Doors</wyk>
			<wyk idwykonawcy="w1">Bullet For My Valentine</wyk>
			<wyk idwykonawcy="w2">TEDE</wyk>
			<wyk idwykonawcy="w3">Opeth</wyk>
			<wyk idwykonawcy="w4">The Offspring</wyk>
		</wykonawcy>
		
    </zbiór>
    
    
    
</płytoteka>
