=== bartoszPawlicki/PCK/OurNamespace.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns="http://tempuri.org/OurNamespace" elementFormDefault="qualified" targetNamespace="http://tempuri.org/OurNamespace" xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="tytułUtworu" type="xs:string" />

  <xs:element name="czasTrwania">
    <xs:simpleType>
      <xs:restriction base="xs:token">
        <xs:pattern value="\d{1,2}:\d{2}"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>

  <xs:element name="cena">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="cenaWartość">
          <xs:attribute name="waluta" use="required">
            <xs:simpleType>
              <xs:restriction base="xs:NMTOKEN">
                <xs:enumeration value="zł" />
                <xs:enumeration value="euro" />
                <xs:enumeration value="dolar" />
              </xs:restriction>
            </xs:simpleType>
          </xs:attribute>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>

  <xs:element name="gatunek">
    <xs:simpleType>
      <xs:restriction base="xs:token">
        <xs:enumeration value="rock" />
        <xs:enumeration value="metalcore" />
        <xs:enumeration value="metal" />
        <xs:enumeration value="progressive-death-metal" />
        <xs:enumeration value="punk-rock" />
        <xs:enumeration value="rap" />
        <xs:enumeration value="pop" />
        <xs:enumeration value="hip-hop" />
        <xs:enumeration value="inny" />
      </xs:restriction>
    </xs:simpleType>
  </xs:element>

  <xs:element name="imię">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:maxLength value="20"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>

  <xs:element name="nazwisko">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:pattern value="[A-Ż][a-ż]{0,20}(-[A-Ż][a-ż]{0,20})?"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>

  <xs:element name="nrIndeksu">
    <xs:simpleType>
      <xs:restriction base="xs:unsignedInt">
        <xs:minInclusive value="111111"/>
        <xs:maxInclusive value="999999"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  
  <xs:element name="opis" type="xs:string" />

  <xs:element name="dataAktualizacji" type="xs:date" />
  
  <xs:element name="dataWydania" type="xs:date" />

  <xs:element name="liczbaUtworów">
    <xs:simpleType>
      <xs:restriction base="xs:decimal">
        <xs:maxInclusive value="50"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  
  <xs:element name="tytuł">
    <xs:simpleType>
      <xs:restriction base="xs:normalizedString">
        <xs:minLength value="2"/>
        <xs:maxLength value="25"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>

  <xs:element name="wykonawca" type="xs:string" />

  <xs:element name="płytoteka">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="nagłówek" />
        <xs:element ref="zbiór" />
      </xs:sequence>
    </xs:complexType>
    
    <xs:key name="nrIndeksuKey">
      <xs:selector xpath="nagłówek/*"/>
      <xs:field xpath="nrIndeksu"/>
    </xs:key>
    
    <xs:unique name="uniqTytułPłyty">
      <xs:selector xpath="zbiór/*"/>
      <xs:field xpath="tytuł"/>
    </xs:unique>
  </xs:element>

  <xs:element name="nagłówek">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="2" maxOccurs="2" ref="autor" />
        <xs:element ref="opis" />
        <xs:element ref="dataAktualizacji" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:group name="dane">
	<xs:sequence>
        <xs:element ref="imię" />
        <xs:element ref="nazwisko" />
        <xs:element ref="nrIndeksu" />
      </xs:sequence>
	</xs:group>
	
  
  <xs:element name="autor">
    <xs:complexType>
      <xs:group ref="dane" />
      <xs:attribute name="id" type="xs:ID" use="required" />
    </xs:complexType>
  </xs:element>

  <xs:simpleType name="cenaWartość">
    <xs:restriction base="xs:decimal">
      <xs:fractionDigits value="2" />
    </xs:restriction>
  </xs:simpleType>

  <xs:element name="lista">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="utwór" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="zbiór">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="płyta" />
      </xs:sequence>
      <xs:attribute name="nazwa" type="xs:NMTOKENS" />
    </xs:complexType>
  </xs:element>

  <xs:element name="utwór">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="tytułUtworu" />
        <xs:element ref="czasTrwania" />
      </xs:sequence>
      <xs:attribute default="mp3" name="codec" use="optional">
        <xs:simpleType>
          <xs:restriction base="xs:NMTOKEN">
            <xs:enumeration value="mp3" />
            <xs:enumeration value="flac" />
            <xs:enumeration value="ogg" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute default="320" name="bitrate" type="xs:short" use="optional"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="płyta">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="tytuł" />
        <xs:element minOccurs="1" maxOccurs="2" ref="wykonawca" />
        <xs:element ref="liczbaUtworów" />
        <xs:element ref="dataWydania"/>
        <xs:element ref="cena"/>
        <xs:element ref="gatunek"/>
        <xs:element name="utwory">
          <xs:complexType>
            <xs:sequence>
              <xs:element ref="lista" />
            </xs:sequence>
            <xs:attribute name="nazwa" type="xs:NMTOKENS" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== bartoszPawlicki/PCK/Pkck5/Pkck5/Dokumenty/plytoteka.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!-- <!DOCTYPE płytoteka SYSTEM "dtdfile.dtd"> /!-->

<?xml-stylesheet type="text/css" href="style.css" ?>

<default:płytoteka xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		   xsi:schemaLocation="http://tempuri.org/OurNamespace OurNamespace.xsd"
		   xmlns:default="http://tempuri.org/OurNamespace"
       xmlns:hn="http://tempuri.org/HeaderNamespace"
       xmlns:ntn="http://tempuri.org/NumericalTypesNamespace">

  <hn:nagłówek>
    <hn:autor id="a1">
      <hn:imię>Bartosz</hn:imię>
        <hn:nazwisko>Pawlicki</hn:nazwisko>
          <ntn:nrIndeksu>195678</ntn:nrIndeksu>
    </hn:autor>
    <hn:autor id="a2">
      <hn:imię>Piotr</hn:imię>
        <hn:nazwisko>Adryjańczyk</hn:nazwisko>
          <ntn:nrIndeksu>195555</ntn:nrIndeksu>
    </hn:autor>
    <hn:opis> Zadanie 3 - Transformacje z użyciem XSLT, cz.1 (XML, XHTML) </hn:opis>
    <hn:dataAktualizacji> 2016-12-11 </hn:dataAktualizacji>
	<hn:klucz>195555</hn:klucz>
  </hn:nagłówek>

  <default:zbiór nazwa="ZBIÓR PŁYT">
    <default:płyta>
      <default:tytuł> L.A. Woman </default:tytuł>
      <default:wykonawca>The Doors</default:wykonawca>
      <ntn:liczbaUtworów> 10 </ntn:liczbaUtworów>
      <default:dataWydania> 1971-05-24 </default:dataWydania>
      <ntn:cena waluta="zł">45</ntn:cena>
      <default:gatunek>rock</default:gatunek>
      <default:utwory nazwa= "Lista utworów">
        <default:lista>
          <default:utwór codec="mp3" bitrate="320">
            <default:tytułUtworu>The Changeling</default:tytułUtworu>
            <ntn:czasTrwania>4:21</ntn:czasTrwania>
          </default:utwór>
          <default:utwór codec="mp3" bitrate="320">
            <default:tytułUtworu>Love Her Madly</default:tytułUtworu>
            <ntn:czasTrwania>3:20</ntn:czasTrwania>
          </default:utwór>
          <default:utwór codec="mp3" bitrate="320">
            <default:tytułUtworu>Riders on the Storm</default:tytułUtworu>
            <ntn:czasTrwania>7:09</ntn:czasTrwania>
          </default:utwór>
        </default:lista>
      </default:utwory>
    </default:płyta>

    <default:płyta>
      <default:tytuł> The Poison </default:tytuł>
      <default:wykonawca>Bullet For My Valentine</default:wykonawca>
      <ntn:liczbaUtworów> 13 </ntn:liczbaUtworów>
      <default:dataWydania> 2005-10-03 </default:dataWydania>
      <ntn:cena waluta="zł">33.33</ntn:cena>
      <default:gatunek>metalcore</default:gatunek>
      <default:utwory nazwa= "Lista utworów">
        <default:lista>
          <default:utwór codec="flac" bitrate="320">
            <default:tytułUtworu>4 Words (To Choke Upon)</default:tytułUtworu>
            <ntn:czasTrwania>2:43</ntn:czasTrwania>
          </default:utwór>
          <default:utwór codec="flac" bitrate="320">
            <default:tytułUtworu>Tears Don't Fall</default:tytułUtworu>
            <ntn:czasTrwania>5:48</ntn:czasTrwania>
          </default:utwór>
          <default:utwór codec="flac" bitrate="320">
            <default:tytułUtworu>All These Things I Hate</default:tytułUtworu>
            <ntn:czasTrwania>3:45</ntn:czasTrwania>
          </default:utwór>
        </default:lista>
      </default:utwory>
    </default:płyta>

    <default:płyta>
      <default:tytuł> VanillaHaj$ </default:tytuł>
      <default:wykonawca> TEDE </default:wykonawca>
      <ntn:liczbaUtworów> 16 </ntn:liczbaUtworów>
      <default:dataWydania> 2016-04-23 </default:dataWydania>
      <ntn:cena waluta="zł">38</ntn:cena>
      <default:gatunek>rap</default:gatunek>
      <default:utwory nazwa= "Lista utworów">
        <default:lista>
          <default:utwór codec="ogg" bitrate="320">
            <default:tytułUtworu>Vanillalalahajs</default:tytułUtworu>
            <ntn:czasTrwania>3:04</ntn:czasTrwania>
          </default:utwór>
          <default:utwór codec="ogg" bitrate="320">
            <default:tytułUtworu>Vanilla Ice</default:tytułUtworu>
            <ntn:czasTrwania>4:22</ntn:czasTrwania>
          </default:utwór>
          <default:utwór codec="ogg" bitrate="320">
            <default:tytułUtworu>Dyskretny chłód 2</default:tytułUtworu>
            <ntn:czasTrwania>3:56</ntn:czasTrwania>
          </default:utwór>
        </default:lista>
      </default:utwory>
    </default:płyta>

    <default:płyta>
      <default:tytuł>Orchid</default:tytuł>
      <default:wykonawca>Opeth</default:wykonawca>
      <ntn:liczbaUtworów> 7 </ntn:liczbaUtworów>
      <default:dataWydania> 1995-05-01 </default:dataWydania>
      <ntn:cena waluta="euro">29.99</ntn:cena>
      <default:gatunek>progressive-death-metal</default:gatunek>
      <default:utwory nazwa= "Lista utworów">
        <default:lista>
          <default:utwór codec="mp3" bitrate="320">
            <default:tytułUtworu>In Mist She Was Standing</default:tytułUtworu>
            <ntn:czasTrwania>14:09</ntn:czasTrwania>
          </default:utwór>
          <default:utwór codec="mp3" bitrate="320">
            <default:tytułUtworu>Under the Weeping Moon</default:tytułUtworu>
            <ntn:czasTrwania>9:55</ntn:czasTrwania>
          </default:utwór>
          <default:utwór codec="mp3" bitrate="320">
            <default:tytułUtworu>Silhouette</default:tytułUtworu>
            <ntn:czasTrwania>3:04</ntn:czasTrwania>
          </default:utwór>
        </default:lista>
      </default:utwory>
    </default:płyta>

    <default:płyta>
      <default:tytuł>Smash</default:tytuł>
      <default:wykonawca>The Offspring</default:wykonawca>
      <ntn:liczbaUtworów> 14 </ntn:liczbaUtworów>
      <default:dataWydania> 1994-04-08 </default:dataWydania>
      <ntn:cena waluta="zł">50.00</ntn:cena>
      <default:gatunek>punk-rock</default:gatunek>
      <default:utwory nazwa= "Lista utworów">
        <default:lista>
          <default:utwór codec="mp3" bitrate="252">
            <default:tytułUtworu>Self Esteem</default:tytułUtworu>
            <ntn:czasTrwania>4:17</ntn:czasTrwania>
          </default:utwór>
          <default:utwór codec="mp3" bitrate="252">
            <default:tytułUtworu>Come Out and Play</default:tytułUtworu>
            <ntn:czasTrwania>3:17</ntn:czasTrwania>
          </default:utwór>
          <default:utwór codec="mp3" bitrate="252">
            <default:tytułUtworu>Nitro (Youth Energy)</default:tytułUtworu>
            <ntn:czasTrwania>2:27</ntn:czasTrwania>
          </default:utwór>
        </default:lista>
      </default:utwory>
    </default:płyta>
    <default:płyta>
      <default:tytuł>Americana</default:tytuł>
      <default:wykonawca>The Offspring</default:wykonawca>
      <ntn:liczbaUtworów> 13 </ntn:liczbaUtworów>
      <default:dataWydania> 2005-01-08 </default:dataWydania>
      <ntn:cena waluta="zł">25.00</ntn:cena>
      <default:gatunek>punk-rock</default:gatunek>
      <default:utwory nazwa= "Lista utworów">
        <default:lista>
          <default:utwór codec="mp3" bitrate="320">
            <default:tytułUtworu>Pretty Fly (for a White Guy)</default:tytułUtworu>
            <ntn:czasTrwania>3:08</ntn:czasTrwania>
          </default:utwór>
          <default:utwór codec="mp3" bitrate="320">
            <default:tytułUtworu>The Kids Aren’t Alright</default:tytułUtworu>
            <ntn:czasTrwania>3:00</ntn:czasTrwania>
          </default:utwór>
          <default:utwór codec="mp3" bitrate="320">
            <default:tytułUtworu>Americana</default:tytułUtworu>
            <ntn:czasTrwania>3:15</ntn:czasTrwania>
          </default:utwór>
        </default:lista>
      </default:utwory>
    </default:płyta>
    <default:płyta>
      <default:tytuł>Americana</default:tytuł>
      <default:wykonawca>The Offspring</default:wykonawca>
      <ntn:liczbaUtworów> 13 </ntn:liczbaUtworów>
      <default:dataWydania> 2005-01-08 </default:dataWydania>
      <ntn:cena waluta="zł">25.00</ntn:cena>
      <default:gatunek>punk-rock</default:gatunek>
      <default:utwory nazwa= "Lista utworów">
        <default:lista>
          <default:utwór codec="mp3" bitrate="320">
            <default:tytułUtworu>Pretty Fly (for a White Guy)</default:tytułUtworu>
            <ntn:czasTrwania>3:08</ntn:czasTrwania>
          </default:utwór>
          <default:utwór codec="mp3" bitrate="320">
            <default:tytułUtworu>The Kids Aren’t Alright</default:tytułUtworu>
            <ntn:czasTrwania>3:00</ntn:czasTrwania>
          </default:utwór>
          <default:utwór codec="mp3" bitrate="320">
            <default:tytułUtworu>Americana</default:tytułUtworu>
            <ntn:czasTrwania>3:15</ntn:czasTrwania>
          </default:utwór>
        </default:lista>
      </default:utwory>
    </default:płyta>
    <default:płyta>
      <default:tytuł>Americana</default:tytuł>
      <default:wykonawca>The Offspring</default:wykonawca>
      <ntn:liczbaUtworów> 13 </ntn:liczbaUtworów>
      <default:dataWydania> 2005-01-08 </default:dataWydania>
      <ntn:cena waluta="zł">25.00</ntn:cena>
      <default:gatunek>punk-rock</default:gatunek>
      <default:utwory nazwa= "Lista utworów">
        <default:lista>
          <default:utwór codec="mp3" bitrate="320">
            <default:tytułUtworu>Pretty Fly (for a White Guy)</default:tytułUtworu>
            <ntn:czasTrwania>3:08</ntn:czasTrwania>
          </default:utwór>
          <default:utwór codec="mp3" bitrate="320">
            <default:tytułUtworu>The Kids Aren’t Alright</default:tytułUtworu>
            <ntn:czasTrwania>3:00</ntn:czasTrwania>
          </default:utwór>
          <default:utwór codec="mp3" bitrate="320">
            <default:tytułUtworu>Americana</default:tytułUtworu>
            <ntn:czasTrwania>3:15</ntn:czasTrwania>
          </default:utwór>
        </default:lista>
      </default:utwory>
    </default:płyta>
    <default:płyta>
      <default:tytuł>Americana</default:tytuł>
      <default:wykonawca>The Offspring</default:wykonawca>
      <ntn:liczbaUtworów> 13 </ntn:liczbaUtworów>
